---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - name: unbound
        image: mvance/unbound-rpi:latest
        ports:
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: unbound-service
  namespace: pihole
spec:
  type: ClusterIP
  selector:
    app: unbound
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
